import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="fixed left-0 top-0">
          <h1 className="text-4xl mb-4">
            <Link href={"/"}>Every Daily Life</Link>
          </h1>
        </header>
        <div className="container mx-auto my-12">
          <div className="flex mx-4">
            <div className="fixed ">
              <Sidebar />
            </div>
            <main className="ml-40 flex-grow">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
